# Generated by Django 3.0.14 on 2021-07-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0002_auto_20210714_0841'),
        ('account', '0003_profile_friends'),
    ]