# Generated by Django 3.0.14 on 2021-07-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0003_auto_20210714_1151'),
        ('account', '0004_auto_20210714_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='user_interests', to='bands.Genre'),
        ),
    ]
