# Generated by Django 3.0.14 on 2021-07-16 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0004_auto_20210716_0752'),
        ('account', '0005_auto_20210714_1151'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
