# Generated by Django 3.0.14 on 2021-06-04 07:51

import bands.models
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50)),
                ('main_genre', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=bands.models.get_upload_path_logo)),
                ('band_picture', models.ImageField(blank=True, null=True, upload_to=bands.models.get_upload_path_band_picture)),
                ('year_of_creation', models.IntegerField(blank=True, help_text='<br>* Molimo vas unesite samo godinu osnivanja radi pravilnog upisa.', null=True)),
                ('members', ckeditor.fields.RichTextField(blank=True, help_text='<br>* Molimo vas unesite samo imena članova benda u ovo polje.', max_length=1000, null=True)),
                ('bio', ckeditor.fields.RichTextField(blank=True, max_length=2000, null=True)),
                ('activity', models.BooleanField(default=False)),
                ('yt_video1', models.CharField(blank=True, max_length=250, null=True)),
                ('yt_video2', models.CharField(blank=True, max_length=250, null=True)),
                ('yt_video3', models.CharField(blank=True, max_length=250, null=True)),
                ('youtube', models.CharField(blank=True, max_length=250, null=True)),
                ('facebook', models.CharField(blank=True, max_length=250, null=True)),
                ('soundcloud', models.CharField(blank=True, max_length=250, null=True)),
                ('instagram', models.CharField(blank=True, max_length=250, null=True)),
                ('band_camp', models.CharField(blank=True, max_length=250, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('admins', models.ManyToManyField(blank=True, related_name='band_admins', to=settings.AUTH_USER_MODEL)),
                ('city_or_town', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Location')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bands.Genre')),
                ('users_follow', models.ManyToManyField(blank=True, related_name='band_follows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name', 'created', 'updated'),
            },
        ),
    ]
