# Generated by Django 3.0.14 on 2021-07-14 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0002_auto_20210714_0841'),
    ]
