# Generated by Django 3.0.14 on 2021-07-16 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0003_auto_20210714_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, default='Serbia', max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='band',
            name='city_or_town',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bands.Location'),
        ),
    ]
